/*! This file was generated by vite-i18n-gen-resources-type check https://github.com/CRMChatReactComponent/vite-i18n-gen-resources-type. Please do not modify. */
export enum GenI18nEnum {
  ZH_CN = "zh-CN",
  EN_US = "en-US",
}
